name: SHRI-VERSE Android Build

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build SHRI-VERSE APK
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Godot project
        uses: NodotProject/godot-export@v7.0.0
        with:
          godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/4.5/Godot_v4.5-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/4.5/Godot_v4.5-stable_export_templates.tpz
          relative_project_path: ./
          export_type: Android
          export_name: SHRI-VERSE.apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: SHRI-VERSE-APK
          path: "**/*.apk"
          if-no-files-found: error
